version: '3.7'

services: 
  db:
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_mysql
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    command: rails server -b 0.0.0.0
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
  front: 
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "8000:3000"
volumes:
  mysql-db:
    driver: local